### PR TITLE
Room Whitelist Server Changes

### PR DESCRIPTION
**Pull request by leralc**
These are the corresponding server changes necessary for the Room Whitelist implementation (interdependent). See the client counterpart for more information: [client!5281](https://gitgud.io/BondageProjects/Bondage-College/-/merge_requests/5281).

### CODE REVIEW

**Comment by Ben987** [comment]
Thank you very much, that's a good idea.  I'll deploy the dev server soon so you can test the client from your side.  Please reach to me on Discord or on GitGud to let me know when the client is tested in the dev environment.  Cheers!

**Comment by leralc** [comment]
Sounds good! Thanks for the quick review.

Looks like the change is not yet deployed to the dev environment, so I'll give it a test once I get back home later today and let you know.

Just a heads-up though that once this change is deployed to dev, older clients attempting to connect to the dev server will likely get "Room Properties Invalid" when trying to create a room as the server fails to find the Whitelist property. There wasn't any checking added server-side to silently add the property since it was expected the client version would be compatible with the server's at all times.

**Comment by zorgjbe** [comment]
Okay, I'm testing that, trying to merge it with the improvements we wanted to make in #183.

Something I notice is that, (ignoring the change that makes private rooms always visible from #183 which I'm now on the fence about), again), you will see private rooms in normal if you're in their whitelist, but not if you're an admin, which feels odd.

Also, I think we want that backward compatibility check added to support the transitional period where the client and server don't match.

**Comment by leralc** [comment]
> Something I notice is that, (ignoring the change that makes private rooms always visible from #183 which I'm now on the fence about), you will see private rooms in normal results if you're in the room's whitelist, but not if you're an admin of it, which feels odd.

That is absolutely true. I'm on the fence on the "whitelist seeing private" feature as a whole (see the [consideration](https://gitgud.io/BondageProjects/Bondage-College/-/merge_requests/5281#whitelisted-users-bypassing-private) on the UI MR). The idea though was to make the changes adhere to the existing BC room style as much as possible, and avoid making sweeping changes to what people expect of private rooms -- leaving any private-bypassing to an explicit whitelist only and not to pair with admins. It does feel a bit strange to me as well though, but I'm not sure what would be the best way to proceed here from:

- Leave private completely unaffected
- Only whitelist bypasses private
- Admin & whitelist bypass private

I have a bit more reasoning on the aforelinked consideration, but this was a quick summary.

> Also, I think we want that backward compatibility check added to support the transitional period where the client and server don't match.

That's a good idea! I'm not sure if there's a set standard for implementing such a check and I'm about to head out in about half an hour as well, so feel free to make the change if you're able. Alternatively, I can take a poke at it tonight or in a few days.

> There's always the Docker stuff to test the server 😉.

Indeed! The server was tested locally already throughout development, but testing again on dev is fine with me -- lets me loop a few more people in anyhow to see if I missed anything while testing.

**Comment by zorgjbe** [comment]
Yeah, since I'd like #183 to move forward, I'll likely revisit a few of those changes there. Already added a few more fields to the room datatype, so the client can tell what's a private/locked room as well, since there's now a case where you will see them even if not doing a "perfect match" query.

At the moment, I changed it so that "admin or whitelist" means the player is a VIP (hello #73). Being a VIP means that you see the room in results whether or not its locked or private (so option 3 above, because it would be weird for the all-powerful user not to be able to join a room as easily as a whitelisted user). For a non-VIP to see a private room they still need to know the room name.

I realize I misread my own change, and the part I was on the fence about in #183 was about locked rooms, whether they should show up in results or not, even though they're inaccessible. So I guess that part will change as well; locked rooms are always visible, unless they're private.

I'll add the back compat check and make sure the client stays working in #183.

**Comment by leralc** [comment]
> Yeah, since I'd like #183 to move forward, I'll likely revisit a few of those changes there. Already added a few more fields to the room datatype, so the client can tell what's a private/locked room as well, since there's now a case where you will see them even if not doing a "perfect match" query.

> I'll add the back compat check and make sure the client stays working in #183.

Perfect! Thanks for all your work :D

> At the moment, I changed it so that "admin or whitelist" means the player is a VIP (hello #73). Being a VIP means that you see the room in results whether or not its locked or private (so option 3 above, because it would be weird for the all-powerful user not to be able to join a room as easily as a whitelisted user). For a non-VIP to see a private room they still need to know the room name.

Seems perfectly reasonable. Probably would be easiest to simply gather feedback on the private change in beta anyway rather than internally considering it.

(also it would've been nice to have known about #73/!2193 when I was working on this 😞, "VIP" was not in my list of terms I thought to search for)

**Comment by zorgjbe** [comment]
Updated #183 with those fixes. Sorry about the unmerged VIP stuff, but yeah… that was a long time ago. Only crash I've found is the old client accidentally deleting the whitelist (since it has no idea it's there), and that's fixed now. Other than that 👍

**Pull request merged**
