### PR TITLE
Lovers feature

### PR DESCRIPTION
**Pull request by Atasly**
based on the work of EveFerox

requires client PR [#618 ](https://github.com/Ben987/Bondage-College/pull/618)to be usable
more details there

updated .gitignore with jetbrains folder

### CODE REVIEW

**Comment by Ben987** [comment]
Can you remove your change to .gitignore?  Thanks

**Comment by Atasly** [comment]
sure, removed it. even if that same line is present as well in the gitignore of the client one and is helpful for those working with jetbrains softwares.

**Comment by Ben987** [comment]
Thanks.  If players are using a previous version of the client without the lovers code in it, will they be able to connect and play on that version of server?  

Can we deploy it before deploying the client?

**Comment by Atasly** [comment]
it should be compatible with current version of the club, the only changes done outside of the new function (AccountLovership) are for a new level of permission (4, owner and lover only) and for a dictionary for server messages (so that we have a message with the name of both players for lovers).
but both should be compatible with current version of the club as it is only additions, just tested the messages of ownership, they are being sent and written fine. (as long as no one is messing with the console, can't predict anything against those...)

**Comment by Ben987** [comment]
Are you able to test your new server version with the previous client?  To see if everything still works?

Thanks a lot

**Comment by Atasly** [comment]
tested the two parts I mentioned (permission and server messages), lovers server with the previous client work great.
haven't tried to break it with console though so can't guarantee anything about that. worst they might be able to do is to get a lover but unable to see or do anything about til the client side comes in.

**Pull request merged**
